"""initial

Revision ID: 2bb088829466
Revises: 
Create Date: 2022-06-06 14:42:43.049627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb088829466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpuperformances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpuperformances')
    # ### end Alembic commands ###
