"""date_time column

Revision ID: d34c8f5bff35
Revises: 2bb088829466
Create Date: 2022-06-06 16:03:28.257746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34c8f5bff35'
down_revision = '2bb088829466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cpuperformances', sa.Column('date_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cpuperformances', 'date_time')
    # ### end Alembic commands ###
