version: '3.7'
services:

  db_algont:
    image: "postgres:13.4-alpine"
    container_name: algontdb

    environment:
      POSTGRES_PASSWORD: 'algont2022'
      POSTGRES_USER: 'algontuser'
      POSTGRES_DB: 'algontdb'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - nginx_network
  nginx_algont:
    image: nginx:latest
    container_name: nginx_algont
    ports:
      - "8080:8080"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./frontend:/frontend

    depends_on:
      - backend_algont
    networks:
      - nginx_network

  backend_algont:
    container_name: backend_algont
    build:
      context: ./config/docker
      dockerfile: ./Dockerfile
    working_dir: /app
    command: bash -c "python -m uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    volumes:
      - ./app:/app
    ports:
      - "8002:8002"
    expose:
      - "8002"
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  pg_data:


